services:

  usuariosapi:
    container_name: app_apiusuarios
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - apiusuarios-network
    depends_on:
      - postgresql
      - rabbitmq
      - mailhog

  postgresql:
    image: postgres:16
    container_name: postgresql_apiusuarios
    restart: always
    ports:
       - "5439:5432"
    environment:
      POSTGRES_DB: bd_apiusuarios
      POSTGRES_USER: user_apiusuarios
      POSTGRES_PASSWORD: pass_apiusuarios
    volumes:
      - apiusuarios-data:/var/lib/postgresql/data
    networks:
      - apiusuarios-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_apiusuarios
    ports:
      - "5672:5672"      # porta para comunicação com apps
      - "15672:15672"    # porta para o painel web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always
    networks:
      - apiusuarios-network

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_apiusuarios
    ports:
      - "8025:8025"      # Web UI
      - "1025:1025"      # SMTP
    restart: always
    networks:
      - apiusuarios-network

volumes:
  apiusuarios-data:

networks:
  apiusuarios-network:
     driver: bridge
