services:

  mysql:
    image: mysql:8.0
    container_name: mysql_apiusuarios
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: coti
      MYSQL_DATABASE: bd_apiusuarios
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_apiusuarios
    ports:
      - "5672:5672"      # porta para comunicação com apps
      - "15672:15672"    # porta para o painel web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog_apiusuarios
    ports:
      - "8025:8025"      # Web UI
      - "1025:1025"      # SMTP
    restart: always

volumes:
  mysql_data:
